### ISSUE TITLE
Upstream updates

### ISSUE THREAD

**Issue by DaRacci** [Bloom-host/Petal#10]
Purpur has a script and github action which runs on a cron schedule that updates from upstream and i think it'd probably be in the best interest to implement something like that here too, If wanted i can make a pr with the required files.

**Comment by Strahilchu** [comment]
I think this would be a good idea once it's out of BETA

**Comment by DaRacci** [comment]
Is there an ETA of when its out of BETA or what?

**Comment by peaches94** [comment]
no eta
