### ISSUE TITLE
Can there be any 1.14.4 virson

### ISSUE THREAD

**Issue by epokuser** [Bloom-host/Petal#13]
1.19 is too much bloated for my potato cpu to run!

**Comment by Strahilchu** [comment]
> 1.19 is too much bloated for my potato cpu to run!

Use BloomHost!

**Comment by epokuser** [comment]
No I want to use my own compooter can there be at least any 1.17 / 1.18 backports as I need it for a plugin!

**Comment by peaches94** [comment]
sorry its not in the plans!
