### ISSUE TITLE
No sound when shooting tridents

### ISSUE THREAD

**Issue by WMGameLive** [Bloom-host/Petal#14]
I am just use petal, not install any plugins, and the problem still exist.
I tested on purpur-1.19.2-1774 and It doesn't have this problem.

**Comment by peaches94** [comment]
could you try latest release?

**Comment by WMGameLive** [comment]
ok, I just tried it. problem still exist.

**Comment by WMGameLive** [comment]
The latest release(pre-7) finally fixed it. Although you didn't reply to me again, still thanks.
