### ISSUE TITLE
"Out-of-order chat packet received. Did your system time change?" Issue

### ISSUE THREAD

**Issue by colton-boi** [Bloom-host/Petal#15]
Seemingly caused by Paper, said to be patched in latest on issue tracker.

**Comment by Strahilchu** [comment]
Set the following, I haven't had this message since I edited these settings as shown

>pufferfish.yml
>disable-out-of-order-chat: true

>purpur.yml
>kick-for-out-of-order-chat: false

**Comment by peaches94** [comment]
try latest too
