### ISSUE TITLE
Not compatible with the new chunk rewrite from paper

### ISSUE THREAD

**Issue by RebelMythik** [Bloom-host/Petal#17]

**Comment by peaches94** [comment]
do you have more info?

**Comment by Pantera07** [comment]
> do you have more info?

![Screenshot_20221003-035657_Discord](https://user-images.githubusercontent.com/89838384/193471254-10fbe189-aee9-4428-bb75-b43eddd331a3.jpg)

**Comment by KurumiFake** [comment]
this shall be closed now ig
