### ISSUE TITLE
KB not working Petal

### ISSUE THREAD

**Issue by LautaKooh** [Bloom-host/Petal#19]
I have a server with the latest version "git-petal-"3efc156" (MC: 1.19.2)" and the KB of the players was deactivated, I don't have any plugin since I took it out thinking it was one of them, and it's still the same without having KB

**Comment by kaxonomy** [comment]
I'm using latest Petal on my server and don't have this issue. Probably plugin-related still.

**Comment by LautaKooh** [comment]
I DO NOT HAVE ANY PLUGIN IN

**Comment by LautaKooh** [comment]
Change the server.jar to purpur and if there is KB
