### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by AndrewChqng** [Bloom-host/Petal#20]
Hi, not sure if I'm doing an issue correctly but on this jar I'm seeing memory usage climb up slowly until it fills up and drops the tps dramatically
I ran spark heapsummary and this was the highest ranked consumer which hasn't happened before on any other paper-forks I've used (very abnormal): 
net.minecraft.server.level.LightEngineThreaded$LightQueue$$Lambda$6739/0x00000008021994e0

Thanks in advance for looking into this! Really appreciated

**Comment by peaches94** [comment]
this can happen on paper too we dont know what causes it yet
