### ISSUE TITLE
crash on start, how can i fix it ?

### ISSUE THREAD

**Issue by Didyouknow-331** [Bloom-host/Petal#22]
crash log file here

---- Minecraft Crash Report ----
// // DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!// Don't be sad. I'll do better next time, I promise!

Time: 2022-10-18 03:53:21
Description: Exception in server tick loop

org.spongepowered.configurate.serialize.SerializationException: [environment, nether-ceiling-void-damage-height] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "disabled"
	at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:346)
	at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254)
	at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40)
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64)
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48)
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204)
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151)
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520)
	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407)
	at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:215)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142)
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: org.spongepowered.configurate.serialize.SerializationException: [fixes, falling-block-height-nerf] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "disabled"
		... 18 more
		Suppressed: org.spongepowered.configurate.serialize.SerializationException: [fixes, tnt-entity-height-nerf] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "disabled"
			... 18 more
		Caused by: java.lang.NumberFormatException: For input string: "disabled"
			at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
			at java.base/java.lang.Integer.parseInt(Integer.java:668)
			at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344)
			... 17 more
	Caused by: java.lang.NumberFormatException: For input string: "disabled"
		at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
		at java.base/java.lang.Integer.parseInt(Integer.java:668)
		at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344)
		... 17 more
Caused by: java.lang.NumberFormatException: For input string: "disabled"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.15.0-50-generic
	Java Version: 17.0.4.1, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 5932434432 bytes (5657 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1270 v5 @ 3.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.60
	Number of physical packages: 2
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: SVGA II Adapter
	Graphics card #0 vendor: VMware (0x15ad)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0x0405
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): -0.00
	Memory slot #0 type: DRAM
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: DRAM
	Virtual memory max (MB): 7062.98
	Virtual memory used (MB): 7229.24
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 1351.89
	JVM Flags: 19 total; -Xms6G -Xmx6G -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15
	CraftBukkit Information: 
   Running: petal version git-petal-"3efc156" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) false
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Reference Handler: [java.base@17.0.4.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17.0.4.1/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@17.0.4.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Finalizer: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@17.0.4.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)], TIMED_WAITING process reaper: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Timer hack thread: [java.base@17.0.4.1/java.lang.Thread.sleep(Native Method), net.minecraft.SystemUtils$7.run(SystemUtils.java:713)], RUNNABLE Notification Thread: [], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.4.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Worker-Main-1: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Common-Cleaner: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.4.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833), java.base@17.0.4.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], RUNNABLE Server thread: [java.base@17.0.4.1/java.lang.Thread.dumpThreads(Native Method), java.base@17.0.4.1/java.lang.Thread.getAllStackTraces(Thread.java:1662), org.bukkit.craftbukkit.v1_19_R1.CraftCrashReport.get(CraftCrashReport.java:33), org.bukkit.craftbukkit.v1_19_R1.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.a(SystemReport.java:62), net.minecraft.CrashReport.<init>(CrashReport.java:38), net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1300), net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1244), net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310), net.minecraft.server.MinecraftServer$$Lambda$4339/0x000000080152bd98.run(Unknown Source), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Java2D Disposer: [java.base@17.0.4.1/java.lang.Object.wait(Native Method), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.desktop@17.0.4.1/sun.java2d.Disposer.run(Disposer.java:145), java.base@17.0.4.1/java.lang.Thread.run(Thread.java:833)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.4.1/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:71), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 200; []
	Data Packs: vanilla, file/bukkit (incompatible)
	World Generation: ERR
	Is Modded: Definitely; Server brand changed to 'petal'
	Type: Dedicated Server (map_server.txt)

**Comment by Warriorrrr** [comment]
The option `nether-ceiling-void-damage-height` expects an integer, you currently have it set to the string "disabled". Change it to 0 instead to disable it.
