### ISSUE TITLE
Plugin applied DARKNESS effect makes player completely blind

### ISSUE THREAD

**Issue by Fenix5fire** [Bloom-host/Petal#27]
If I apply darkness effect to player using plugin (tested with ConditionalEvents and Denizen) it makes player absolutely blind, which is not vanilla behavior.
But if effect applied by vanilla /effect command it works properly.

Issue does not exist on Purpur and below

Applied by plugin:
![image](https://user-images.githubusercontent.com/62252856/204032345-18b4a967-30c5-46da-a9c4-4f948ba168b8.png)

Applied by vanilla command:
![image](https://user-images.githubusercontent.com/62252856/204032441-6c11d8a3-ccd0-458b-9751-f811dd25bc58.png)

**Comment by Matt-MX** [comment]
Seems alright for me, could this be a client issue? That's more likely.

**Comment by Fenix5fire** [comment]
> Seems alright for me, could this be a client issue? That's more likely.

It's full vanilla 1.19.2 and is not a thing on Purpur and below. How could it be client issue? It is possible that plugins I used may not be perfect in that case (which is unlikely), but it's issue anyway.

**Comment by KioProject123** [comment]
may be this reason
https://github.com/PurpurMC/Purpur/issues/1181

**Comment by Fenix5fire** [comment]
> may be this reason [PurpurMC/Purpur#1181](https://github.com/PurpurMC/Purpur/issues/1181)

Yes, it is. Looks like it's fixed since Purpur build 1836. I have tested on 1850 and it worked as expected.

**Comment by Fenix5fire** [comment]
Fixed in Petal 1.19.2 pre-9
