### ISSUE TITLE
Bug when interacting with Villagers

### ISSUE THREAD

**Issue by TehMartinXz** [Bloom-host/Petal#8]
Posted this yesterday on Discord and didn't have time to make an issue here.

Found a bug with this build (doesn't occurs on pre release 2). Happens when interacting with villagers:
https://bin.bloom.host/gogatodufa.properties

A direct effect of it is that the villager itself disappears when interacting

Version: git-petal-"7b3fb09"

**Comment by peaches94** [comment]
https://github.com/Bloom-host/Petal/releases/tag/1.19-pre-3
