### ISSUE TITLE
Server crash last build

### ISSUE THREAD

**Issue by XionioXMaster** [Bloom-host/Petal#9]
Crash intensively memory is not full, CPU is not limited

https://gist.github.com/XionioXMaster/70b56fefd4f2382c7bcab938660c17c2

**Comment by XionioXMaster** [comment]
![Без имени](https://user-images.githubusercontent.com/86433158/181055103-71baa283-83f8-494f-8e12-dfb383b859a9.png)
Something to do with the mobs, the CPU starts to gain momentum and does not fall below 600% as if they are not unloading. As a result, it rises to 1100% and crashes the server at the peak frequency. As soon as I wrote /gamerule doMobSpawning false and killed the mobs, the load dropped to 200%

**Comment by XionioXMaster** [comment]
Although no, he is again overloaded

**Comment by peaches94** [comment]
try the new build!
